### ISSUE TITLE
TravisCI failing on node 8

### ISSUE THREAD

**Issue by thebinarypenguin** [thebinarypenguin/scribblez-rest-api-server#2]
The build fails because lab detects a leak and fails the tests

```
The following leaks were detected:WebAssembly
```

I think this is fixed in newer versions of lab.

**Comment by thebinarypenguin** [comment]
Fixed by updating to the latest lab version

**Comment by danielo515** [comment]
@thebinarypenguin would you mind to share the exact version ?
